### ISSUE TITLE
Usage Documentation

### ISSUE THREAD

**Issue by Boykai** [Azure/Synapse-workspace-deployment#13]
Any documentation on how to use this repo would be great. 

I am trying to do a simple clone/redeploy from my existing Synapse Workspace to a new Synapse Workspace, this repo seems to fit but there is minimal documentation.

**Comment by lordozb** [comment]
Hello
We have a github action available on the marketplace. You can directly use that instead of using this repository.
https://github.com/marketplace/actions/synapse-workspace-deployment

Please let me know if any additional help is required.
