### ISSUE TITLE
Action inputs missing/confusing

### ISSUE THREAD

**Issue by ivarostby** [Azure/Synapse-workspace-deployment#14]
Missing action input for "DeleteArtifactsNotInTemplate":
const deleteArtifactsNotInTemplateString = core.getInput("DeleteArtifactsNotInTemplate");

`Warning: Unexpected input(s) 'DeleteArtifactsNotInTemplate', valid inputs are ['TargetWorkspaceName', 'TemplateFile', 'ParametersFile', 'OverrideArmParameters', 'Environment', 'resourceGroup', 'clientId', 'clientSecret', 'subscriptionId', 'tenantId', 'activeDirectoryEndpointUrl', 'resourceManagerEndpointUrl']`

**Comment by lordozb** [comment]
Hello 
This is still in master branch and not yet released.
