### ISSUE TITLE
Deployment Error with activ Trigger

### ISSUE THREAD

**Issue by juergenkaufmann** [Azure/Synapse-workspace-deployment#27]
Hello,

when we deploy the  to the test Synapse Enviroment and some Trigger are activ we getting this Error:

WorkspaceType:<Synapse>] Job was submitted with resources=[24] when the compute has a capacity of=[12]

We need to aktivate some off the definied Triggers from the Develop Enviroment. 
For Deployment we are using the mater Branch.

**Comment by lordozb** [comment]
We are working on toggle trigger action. We will be supporting it both in azure devops extension and Github action.

**Comment by juergenkaufmann** [comment]
Thanks.
Hope we get the changes in the next few Month.

**Comment by lordozb** [comment]
Closing the issue for now.
