### ISSUE TITLE
Trigger Issue on Deployment

### ISSUE THREAD

**Issue by cpc-fitzgd** [Azure/Synapse-workspace-deployment#46]
We're seeing the following error during deployment when we don't disable all triggers on the deployment target:

```
Action failed -> Error: Orchestrate failed - Error: Failed to fetch the deployment status {"code":"TriggerEnabledCannotUpdate","message":"Cannot update enabled Trigger; the trigger needs to be disabled first. "}
```

We're told that the ADO version of this same action doesn't require triggers to be turned off at the target. Are we doing something incorrectly or is this an issue with this GitHub Action?

**Comment by lordozb** [comment]
Hello @cpc-fitzgd 
The ADO version also requires the triggers to be disabled. There is an extension available in ADO which can be used to enable/ disabled trigger.s

We are working on providing it for Github action as well but there is no ETA as of now.
