### ISSUE TITLE
Promotion failure when using datalake tables 

### ISSUE THREAD

**Issue by hdmillert17** [Azure/Synapse-workspace-deployment#48]
Hey team,

I'm experiencing an issue where promotion fails intermittently when using datalake tables. 14 of my past 25 deployment attempts have failed. This issue does not seem to be correlated to changes in the datalake tables themselves.

Error:
For artifact: temp: Checkstatus: 200; status message: OK
Action failed -> Error: Orchestrate failed - Error: Artifiact deployment validation failed

Unfortunately the Orchestrate error does not populate an error to usefully debug. Also minor fix: Artifact is spelled wrong in check status function.

Please let me know what additional information I can provide.

**Comment by lordozb** [comment]
Hello @hdmillert17 
Can you please also share details such as workspace name, the region where the workspace is located, datalake name, table name and the time around which the deployment failed.

**Comment by hdmillert17** [comment]
@lordozb 

I appreciate your reply! If we're going to be discussing account specifics, I'd rather not do it across a public github issue.  Is there a MSFT email address that I can reach you at? 

Thanks!

**Comment by lordozb** [comment]
Hello @hdmillert17 
You can reach out at : Synapse-CICD@service.microsoft.com

**Comment by lordozb** [comment]
Hello @hdmillert17 
V1.4.0 should fix the issue. Please feel free to re-open issue or reach out to us on the above email.
