### ISSUE TITLE
DeleteArtifactsNotInTemplate - Orchestration Sequence Issue

### ISSUE THREAD

**Issue by jeannejin** [Azure/Synapse-workspace-deployment#56]
**Issue Description**: current process sequence of section 'DeleteArtifactsNotInTemplate' in 'orchestrator.ts' file is ahead of deployment. Deployment fail in following scenario: 
 Step 1:  'Pipline1' has an dataflow activity 'dataflow1', hence 'dataflow1' is calling from 'Pipeline1'. Initial deployment succeed
  Step 2: Updated 'Pipeline1' artifact by remove activity 'dataflow1'. Then delete dataflow 'dataflow1' since it is no longer needed
  Step 3: Deploy again, it fails, error message is 

_2022-05-12T17:33:14.9428660Z The document cannot be deleted since it is referenced by Pxxxxxxn.
2022-05-12T17:33:14.9433308Z Error during execution: Error: For Artifact: Bxxxxxxg deletion failed. {"status":"Failed","error":{"code":"DeleteDataFactoryResourceOrchestrationError","message":"The document cannot be deleted since it is referenced by Pxxxxxxn."}}
2022-05-12T17:33:14.9471695Z ##[error]Encountered with exception:Error: For Artifact: Bxxxxxxg deletion failed. {"status":"Failed","error":{"code":"DeleteDataFactoryResourceOrchestrationError","message":"The document cannot be deleted since it is referenced by Pxxxxxxn."}}_

**Work around**: run deployment twice, first time with 'DeleteArtifactsNotInTemplate' set to 'false', and deploy again with 'DeleteArtifactsNotInTemplate' set to 'true'

**Suggest Solution**: In orchestrator.ts file, move 'DeleteArtifactsNotInTemplate' after deployment

**Comment by lordozb** [comment]
Hello @jeannejin 
The team will look into it and will come up with a fix.

**Comment by jeannejin** [comment]
Hi,

Thanks for the message. This is my first time to raise an issue in GitHub. I was wondering what is going to happen.

When it is fixed, would you please let me know? I will update my deployment pipeline to remove the walkaround. It double the deployment time now. 🙂

Thanks
Jeanne
________________________________

**Comment by lordozb** [comment]
Hello @jeannejin 
Sure, I'll update it here.

Thanks.

**Comment by lordozb** [comment]
The fix has been released. Please use V1.6.0
