### ISSUE TITLE
User Assigned Identity & managed PEs - Template not exposing resource ID as parameter

### ISSUE THREAD

**Issue by marvinbuss** [Azure/Synapse-workspace-deployment#58]
My workspace has a user assigned identity defined as credential. The exported template from my development workspace includes the credential, but with a hard-coded resource ID. My second workspace is using a different user assigned identity. This seems to be a bug wrt how the template is generated when publishing the template in the development workspace.
Why is the resource ID not parametrized?
Can this be changed in the source workspace, so that the resource ID is exposed as parameter in the template?

Thanks for your help!

**Comment by lordozb** [comment]
You can create custom parameters. https://docs.microsoft.com/en-us/azure/synapse-analytics/cicd/continuous-integration-delivery#create-custom-parameters-in-the-workspace-template

Please don't use Issues to ask questions, create a support ticket on Azure portal instead.
