### ISSUE TITLE
Managed Private Endpoints

### ISSUE THREAD

**Issue by tobimax** [Azure/Synapse-workspace-deployment#63]
Hi,

We have a scenario where we do not want to deploy Development MPEs into different (Test/Prod) as they point to different resources. However, we also do not want to leave orphaned objects in the target that are not in the deployment.

The following settings remove the MPEs and the orphaned objects not in the build.
```
DeleteArtifactsNotInTemplate: true
DeployManagedPrivateEndpoints: false
```
The following settings deploy the Development MPEs to Test/Prod which isn't relevant and also removes the existing MPEs and orphaned objects that are not in the build.
```
DeleteArtifactsNotInTemplate: true
DeployManagedPrivateEndpoints: true
```
Removing the settings and allowing for the default ignores the MPEs but leaves in place the orphaned objects that are not in the build.

**I need this task to** 

Remove the orphaned objects that are not in the build and leave the MPEs alone that already exist in Test/Prod and not deploy the development MPEs.

Could you please look into the issue?

Thanks

Toby.

**Comment by lordozb** [comment]
Closing it here because already opened on Azure devops marketplace.
