### ISSUE TITLE
Update README on usage of validateDeploy

### ISSUE THREAD

**Issue by vermegi** [Azure/Synapse-workspace-deployment#67]
The README isn't very clear on the exact usage of validateDeploy operations when you also want to replace parameters. 

- In that case you shouldn't use the `ParametersFile` parameter on the action, but the `OverrideArmParameters` parameter. 
- Also, it is not obvious that `ArtifactsFolder` should be set to `$GITHUB_WORKSPACE`. 

Full sample for this: 

name: ValidateAndDeploy

on:
  workflow_dispatch

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        
        - uses: Azure/synapse-workspace-deployment@V1.7.0
          with:
            TargetWorkspaceName: 'synapse-tryout-prod'
            ArtifactsFolder: '$GITHUB_WORKSPACE'
            environment: 'Azure Public'
            resourceGroup: 'synapse-tryout'
            clientId: ${{ secrets.CLIENTID }}
            clientSecret: ${{ secrets.CLIENTSECRET }}
            subscriptionId: ${{ secrets.SUBID }}
            tenantId: ${{ secrets.TENANTID }}
            operation: 'validateDeploy'
            OverrideArmParameters: 'myparams.yml'

        - uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: ./ExportedArtifacts

Additionally, add to the README a sample on 2 step deploy, where validate is run first and then deploy: 

name: ValidateAndDeploy2Steps

on:
  workflow_dispatch

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - uses: Azure/synapse-workspace-deployment@V1.7.0
          with:
            TargetWorkspaceName: 'synapse-tryout-prod'
            ArtifactsFolder: '$GITHUB_WORKSPACE'
            operation: 'validate'

        - uses: Azure/synapse-workspace-deployment@V1.7.0
          with:
            TargetWorkspaceName: 'synapse-tryout-prod'
            TemplateFile: './ExportedArtifacts/TemplateForWorkspace.json'
            ParametersFile: './myparams.json'
            environment: 'Azure Public'
            resourceGroup: 'synapse-tryout'
            clientId: ${{ secrets.CLIENTID }}
            clientSecret: ${{ secrets.CLIENTSECRET }}
            subscriptionId: ${{ secrets.SUBID }}
            tenantId: ${{ secrets.TENANTID }}
            operation: 'deploy'

        - uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: ./ExportedArtifacts

**Comment by lordozb** [comment]
Hello @vermegi 

1. Parameters file correspond to the parameters file generated by the Synapse workspace. OverrideArmParameters should always be used for over riding the parameters as mentioned in the READ ME - https://github.com/Azure/Synapse-workspace-deployment#overriding-parameters-overridearmparameters
2. 'Validate' command is not supposed to be executed before 'deploy'. Deploy takes template and parameter files generated by the synapse workspace for the workspace publish branch. validate command generates template and parameter files from the collaboration branch. 
3. There is no need to specify  ArtifactsFolder: '$GITHUB_WORKSPACE' as it is by default the location. You can directly access the folder.

**Comment by vermegi** [comment]
Then what about the way of working that is described here: https://techcommunity.microsoft.com/t5/azure-synapse-analytics-blog/automating-the-publishing-of-workspace-artifacts-in-synapse-cicd/ba-p/3603042 
Thisvway of working does not always start from the collaboration/publish branch.
