### ISSUE TITLE
sqlPool object is missing from TemplateForWorkspace.json after validate

### ISSUE THREAD

**Issue by jdwilkin** [Azure/Synapse-workspace-deployment#68]
I am using the 'validate' option as part of a DevOps pipeline and the TemplateForWorkspace.json file is missing the reference to the sqlPool in one of the datasets defined.  When publishing the end result is the dataset is not properly linked to the dedicated pool and thus none of the synapse pipelines that use that dataset work.

**Comment by jdwilkin** [comment]
Here is the segment from TemplateForWorkspace created from the "publish" button in synapse studio:
{
			"name": "[concat(parameters('workspaceName'), '/LumenRiskSynapseDB')]",
			"type": "Microsoft.Synapse/workspaces/datasets",
			"apiVersion": "2019-06-01-preview",
			"properties": {
				"parameters": {
					"DB_Name": {
						"type": "string"
					},
					"Table_Name": {
						"type": "string"
					}
				},
				"annotations": [],
				"type": "SqlPoolTable",
				"schema": [],
				"typeProperties": {
					"schema": {
						"value": "@dataset().DB_Name",
						"type": "Expression"
					},
					"table": {
						"value": "@dataset().Table_Name",
						"type": "Expression"
					}
				},
				"sqlPool": {
					"referenceName": "lumenanalyticsdb",
					"type": "SqlPoolReference"
				}
			},
			"dependsOn": [
				"[concat(variables('workspaceId'), '/sqlPools/lumenanalyticsdb')]"
			]
		}

And here is the relevant segment using this plugin:
{
            "name": "[concat(parameters('workspaceName'), '/LumenRiskSynapseDB')]",
            "type": "Microsoft.Synapse/workspaces/datasets",
            "apiVersion": "2019-06-01-preview",
            "properties": {
                "parameters": {
                    "DB_Name": {
                        "type": "string"
                    },
                    "Table_Name": {
                        "type": "string"
                    }
                },
                "annotations": [],
                "type": "SqlPoolTable",
                "schema": [],
                "typeProperties": {
                    "schema": {
                        "value": "@dataset().DB_Name",
                        "type": "Expression"
                    },
                    "table": {
                        "value": "@dataset().Table_Name",
                        "type": "Expression"
                    }
                }
            },
            "dependsOn": []
        }

notice the missing 'sqlPool' object

**Comment by lordozb** [comment]
The fix is currently being tested. This should be released soon. 
You will not be required to update anything on your end.

**Comment by ArthurSteijn** [comment]
Is this fix for the GitHub Actions task only? Or for the Azure DevOps task as well?

**Comment by lordozb** [comment]
@ArthurSteijn  For both

**Comment by jdwilkin** [comment]
Was this closed because the fix was released?

**Comment by lordozb** [comment]
Yes, it has been released.

**Comment by jdwilkin** [comment]
Thank you for the update... I am using this plugin in Azure Pipelines do you know if the azure pipeline version has been release as well?

**Comment by lordozb** [comment]
Yes it has been released.

**Comment by jdwilkin** [comment]
for reference here is a microsoft feedback issue referencing the same:
https://developercommunity.visualstudio.com/t/Synapse-workspace-deployment2-SqlPoolTa/10202235?viewtype=all

**Comment by lordozb** [comment]
I mentioned earlier that no action will be required from your side. The package with the fix is downloaded during runtime. You don't need to update the extension.

**Comment by jdwilkin** [comment]
my testing today and yesterday show the same problem, namely the sqlPool object is not correctly created in the dataset.

**Comment by jdwilkin** [comment]
Maybe this is the wrong place for this as this is specific to the GitHub action, however this problem still exists when using the plugin from Azure Devops.  If there is a better place to open this please let me know otherwise this ticket should be reopened

**Comment by lordozb** [comment]
Please raise a support ticket on Azure portal.
