### ISSUE TITLE
Validate throws strange export error

### ISSUE THREAD

**Issue by ychen4-li** [Azure/Synapse-workspace-deployment#72]
Validate step is throwing strange error that I have not seen before and I haven't change to action file for a while.

- name: Validate synapse workspace
        uses: Azure/Synapse-workspace-deployment@V1.7.0
        with:
          TargetWorkspaceName: ${{ inputs.workspace_name }}
          ArtifactsFolder: ${{ inputs.artifacts_folder }}
          operation: 'validate'

Error:
ERROR === CmdApiApp: Failed to export Synapse template. Error: {"stack":"Error: Failed to generate ARM template. One or more resources are bad, fix them and retry the operation again., resource name: [object Object]\n

**Comment by lordozb** [comment]
Hello @ychen4-li 
Please raise a support ticket on azure portal. The team will look into it.

**Comment by ychen4-li** [comment]
It seems like related to pipeline spark pool reference on notebook, I used dynamic content and it worked before, not sure what broke it. My workaround is to not use dynamic content.
