### ISSUE TITLE
Federated credentials (OIDC) Support for Azure Authentication

### ISSUE THREAD

**Issue by s-yadkikar** [Azure/Synapse-workspace-deployment#76]
Any plans to support Azure authentication with OIDC?
[GitHub OIDC Azure Login](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#use-the-azure-login-action-with-openid-connect)

**Comment by joeysun-vw** [comment]
+1 for follow

**Comment by lordozb** [comment]
Hello

Currently, there are no plans to support this.
